### ISSUE TITLE
JWT_REFRESH_TOKEN_EXPIRES not used

### ISSUE THREAD

**Issue by jhorman** [callsign-viper/Flask-GraphQL-Auth#5]
I don't see where `JWT_REFRESH_TOKEN_EXPIRES` is actually used in the code base.

**Comment by devArtoria** [comment]
Hi jhorman, 
 
I'm glad you're interested in our project! this issue has just been fixed in commit [9fe55b1](https://github.com/callsign-viper/Flask-GraphQL-Auth/commit/9fe55b19f86323da2df24dee4a464116c1f182ad) 
Thank you for letting us know.

**Comment by jhorman** [comment]
Thanks!

**Comment by devArtoria** [comment]
Your welcome 😚
